### ISSUE TITLE
Compatibility with Zabbix 4.x

### ISSUE THREAD

**Issue by MarekGrossman** [burner1024/zabbix-sql#4]
Hello,
      can I use "*.zbx3.sql" queries for Zabbix 4.2 or do you will prepare new files?

Thanks for answer
--
Mareg

**Comment by burner1024** [comment]
I don't have a Zabbix 4 installation now, so I don't know how well will the queries work.
Best advice I can give is make a backup, test the queries, and if needed, fix and submit a pull request.
