### ISSUE TITLE
Update for actual version of Zabbix

### ISSUE THREAD

**Issue by franciscotudel-overtel** [burner1024/zabbix-sql#5]
Hi from spain!

first of all, THANK YOU VERY MUCH for your scripts! I work with them on every of my zabbix instances :-)

I'm not an expert on zabbix but have done some work with it, monitorizing Veeam Jobs.. Sql Servers...

No problem with scripts, only a question:

Can you update for newer versions of software?
I supose more people like me use this from each to each time and perhaps not very difficult for you.

Thanks for your time.

**Comment by burner1024** [comment]
I don't have a working Zabbix installation at the moment, so I can't develop or test the scripts. You're welcome to submit pull requests, however.
